name: Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      homedrive:
        description: Home Directory
        type: text
        required: true

      logLevel:
        description: choice
        type: choice
        default: one
        options:
          - one
          - two
          - three
          
jobs:
  AnotherJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"

      - run: echo "${{ options.logLevel }}"
