name: Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      homedrive:
        description: Home Directory
        type: text
        required: true

      logLevel:
        description: choice
        type: choice
        default: one
        options:
          - one
          - two
          - three
          
